// This is loaded into the PhantomJs browser - do not edit - this is auto-generated by Gruntfile.js 
var __dirname = 'D:\html5 projects\Examples\Fantoo Test';
var __dirnameglobal = 'D:\html5 projects\Examples\Fantoo Test';